// src/components/guest-view/GuestServiceState.tsx
import { observer } from 'mobx-react-lite';

import { useTranslation } from '../../stores/react/use-translation';
import { GuestScheduleDetails } from './GuestScheduleDetails';
import { GuestStateMessage } from './GuestStateMessage';

export type GuestServiceStateProps = {
	/** `false` while service is underway (`service_started`); `true` once the session has `ended`. */
	hasEnded: boolean;
};

/**
 * Service is underway, or over. Only the ended state offers the schedule: while the market is
 * running there is nothing to come back for.
 */
export const GuestServiceState = observer(function GuestServiceState({
	hasEnded,
}: GuestServiceStateProps) {
	const t = useTranslation();
	const copy = hasEnded
		? {
				heading: t.guestView.serviceState.endedHeading,
				description: t.guestView.serviceState.endedDescription,
			}
		: {
				heading: t.guestView.serviceState.inProgressHeading,
				description: t.guestView.serviceState.inProgressDescription,
			};

	return (
		<GuestStateMessage
			heading={copy.heading}
			description={copy.description}
			details={hasEnded ? <GuestScheduleDetails /> : undefined}
		/>
	);
});

// src/components/guest-view/GuestServiceState.vue
<script setup lang="ts">
import { computed } from 'vue';

import type { Translation } from '../../locales';
import GuestScheduleDetails from './GuestScheduleDetails.vue';
import GuestStateMessage from './GuestStateMessage.vue';

const props = defineProps<{
	t: Translation;
	/** `false` while service is underway (`service_started`); `true` once the session has `ended`. */
	hasEnded: boolean;
}>();

const copy = computed(() =>
	props.hasEnded
		? {
				heading: props.t.guestView.serviceState.endedHeading,
				description: props.t.guestView.serviceState.endedDescription,
			}
		: {
				heading: props.t.guestView.serviceState.inProgressHeading,
				description: props.t.guestView.serviceState.inProgressDescription,
			},
);
</script>

<template>
	<GuestStateMessage :heading="copy.heading" :description="copy.description">
		<template v-if="hasEnded" #details>
			<GuestScheduleDetails :t="t" />
		</template>
	</GuestStateMessage>
</template>
