// src/components/guest-view/GuestNotOpenState.tsx
import styled from '@emotion/styled';
import { observer } from 'mobx-react-lite';

import { useTranslation } from '../../stores/react/use-translation';
import { GuestStateMessage } from './GuestStateMessage';

const Message = styled(GuestStateMessage)`
	--state-description-max-width: 420px;
`;

const Details = styled.div`
	display: grid;
	max-width: 420px;
	gap: 16px;
	margin-top: 20px;
	color: var(--color-text-muted);
	line-height: 1.55;
	text-align: justify;
	text-align-last: start;
	hyphens: auto;
`;

const Divider = styled.hr`
	width: 100%;
	max-width: 420px;
	margin: 24px 0 0;
	border: 0;
	border-top: 1px solid var(--color-border);
`;

/** The market is closed: when it next opens, how the lottery works, and how to hear about it. */
export const GuestNotOpenState = observer(function GuestNotOpenState() {
	const t = useTranslation();
	const copy = t.guestView.notOpenState;

	return (
		<Message className="inactive-message" heading={copy.heading} description={copy.subheading}>
			<Divider />
			<Details className="inactive-details">
				<p>{copy.lotteryDescription}</p>
				<p>{copy.selectionDescription}</p>
			</Details>
		</Message>
	);
});

// src/components/guest-view/GuestNotOpenState.vue
<script setup lang="ts">
import { useRouter } from 'vue-router';

import AppButton from '@/components/AppButton.vue';

import type { Translation } from '../../locales';
import GuestStateMessage from './GuestStateMessage.vue';

const router = useRouter();

defineProps<{ t: Translation }>();

function goToSignup() {
	void router.push({ name: 'signup' });
}
</script>

<template>
	<GuestStateMessage
		class="inactive-message"
		:heading="t.guestView.notOpenState.heading"
		:description="t.guestView.notOpenState.subheading"
	>
		<AppButton @click="goToSignup"> Preregister </AppButton>
		<div class="inactive-details">
			<p>{{ t.guestView.notOpenState.lotteryDescription }}</p>
			<p>{{ t.guestView.notOpenState.selectionDescription }}</p>
		</div>
	</GuestStateMessage>
</template>

<style scoped>
.inactive-message {
	--state-description-max-width: 420px;
}
.inactive-details {
	display: grid;
	max-width: 420px;
	gap: 16px;
	margin-top: 20px;
	color: var(--color-text-muted);
	line-height: 1.55;
	text-align: justify;
	text-align-last: start;
	hyphens: auto;
}
</style>
