// src/components/guest-view/GuestView.tsx
import { observer } from 'mobx-react-lite';
import { useEffect, useState } from 'react';

import type { Locale } from '../../locales';
import {
	currentSessionPhase,
	guestFormContext,
	resolveGuestCardState,
} from '../../services/guestCardState';
import { SessionStatusEnum } from '../../services/sessionStateMachine';
import { useRootStore } from '../../stores/react/store-context';
import { useTranslation } from '../../stores/react/use-translation';
import type { RegistrationSubmitResult } from '../../stores/registration.store';
import type { Language } from '../../stores/translation.store';
import { Card } from '../ui/layout/Card';
import { GuestIdentityIndicator } from './GuestIdentityIndicator';
import { GuestLanguageHero } from './GuestLanguageHero';
import { GuestNotOpenState } from './GuestNotOpenState';
import { GuestRegistrationClosedState } from './GuestRegistrationClosedState';
import { GuestRegistrationForm } from './GuestRegistrationForm';
import { GuestServiceState } from './GuestServiceState';
import { GuestVisitStatus } from './GuestVisitStatus';

/** The guest home screen (`/`): identity, language, and whichever card the session phase calls for. */
export const GuestView = observer(function GuestView() {
	const t = useTranslation();
	const rootStore = useRootStore();
	const { guest, session, visit, translations } = rootStore;

	const [isStatusLoading, setIsStatusLoading] = useState(true);
	/** Ticks every second so the registration form's countdown stays live. */
	const [now, setNow] = useState(() => Date.now());

	useEffect(() => {
		const timer = setInterval(() => setNow(Date.now()), 1_000);

		return () => clearInterval(timer);
	}, []);

	useEffect(() => {
		let cancelled = false;

		void Promise.all([session.getStatus().catch(() => undefined), visit.refresh()]).then(() => {
			if (!cancelled) {
				setIsStatusLoading(false);
			}
		});

		return () => {
			cancelled = true;
		};
	}, [session, visit]);

	function selectLanguage(selected: Locale) {
		translations.setLanguage(selected as Language);
		guest.markAsReturningVisitor();
	}

	function handleSubmitted(result: RegistrationSubmitResult) {
		if (result.kind !== 'registered') {
			return;
		}

		visit.submit(result.registration);
	}

	function cancelVisit() {
		if (!window.confirm(t.cancelVisitConfirm)) {
			return;
		}

		void visit.cancel();
	}

	/**
	 * Whether `/api/market` has ever returned usable data. Stays `false` while it hasn't, including
	 * when the optional configuration endpoint can't be reached — the phase below treats that the
	 * same as registration being open, so the form is still available rather than blocking a guest
	 * behind a "not open" screen the app can't actually confirm.
	 */
	const hasLoadedRegistration = session.currentState !== null;
	const phase = hasLoadedRegistration
		? currentSessionPhase(session.marketEvent, new Date(now))
		: 'registration-open';
	/**
	 * Which of the signup card's states applies right now. An active visit always wins — see
	 * `resolveGuestCardState` for the full precedence, which mirrors the server-side gate in
	 * `guestRegistration.mts`. `isPreregistration` is always `false` here — the `/signup` route
	 * renders `SignupView` instead, which is the only place that flag ever applies.
	 */
	const cardState = resolveGuestCardState({
		phase,
		isIdentified: guest.isIdentified,
		isPreregistration: false,
		hasActiveVisit: visit.hasActiveVisit,
	});
	/**
	 * Once a market has run its course, there is nothing left to preregister for until an admin
	 * schedules the next one — unlike the "hasn't opened yet" case, which still welcomes it.
	 */
	const canPreregister = session.currentStatus !== SessionStatusEnum.ENDED;
	/** The success-state copy differs between joining today's queue and signing up ahead of time. */
	const successCopy =
		guestFormContext(phase) === 'early'
			? { title: t.earlySuccessTitle, description: t.earlySuccessDescription }
			: { title: t.successTitle, description: t.successDescription };

	return (
		<section className="guest-layout">
			{/* Card that indicates who the guest has been identified as */}
			{guest.identity ? <GuestIdentityIndicator identity={guest.identity} /> : null}

			{!guest.isReturningVisitor ? <GuestLanguageHero onSelectLanguage={selectLanguage} /> : null}

			{isStatusLoading ? (
				<p className="status-loading" aria-live="polite">
					{t.statusLoading}
				</p>
			) : (
				<Card aria-live="polite">
					{!session.isActive ? (
						<GuestNotOpenState allowPreregister={canPreregister} />
					) : cardState.kind === 'visit-status' ? (
						<GuestVisitStatus
							successTitle={successCopy.title}
							successDescription={successCopy.description}
							onCancelVisit={cancelVisit}
						/>
					) : cardState.kind === 'form' ? (
						<GuestRegistrationForm
							context={cardState.context}
							now={now}
							onSubmitted={handleSubmitted}
						/>
					) : cardState.kind === 'not-open' ? (
						<GuestNotOpenState />
					) : cardState.kind === 'registration-closed' ? (
						<GuestRegistrationClosedState />
					) : (
						<GuestServiceState hasEnded={cardState.kind === 'ended'} />
					)}
				</Card>
			)}
		</section>
	);
});

// src/components/guest-view/GuestView.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue';

import Card from '@/components/ui/layout/Card.vue';
import { GuestRegistrationForm } from '@/react-bridge/islands.ts';
import { fromMobx } from '@/stores/hooks/from-mobx.ts';

import type { Locale } from '../../locales';
import {
	currentSessionPhase,
	guestFormContext,
	resolveGuestCardState,
} from '../../services/guestCardState';
import { SessionStatusEnum } from '../../services/sessionStateMachine';
import type { RegistrationSubmitResult } from '../../stores/registration.store';
import { useRootStore } from '../../stores/root.store';
import type { Language } from '../../stores/translation.store';
import GuestIdentityIndicator from './GuestIdentityIndicator.vue';
import GuestLanguageHero from './GuestLanguageHero.vue';
import GuestNotOpenState from './GuestNotOpenState.vue';
import GuestRegistrationClosedState from './GuestRegistrationClosedState.vue';
import GuestServiceState from './GuestServiceState.vue';
import GuestVisitStatus from './GuestVisitStatus.vue';

const rootStore = useRootStore();
const guestDomain = rootStore.guest;
const session = rootStore.session;
const visitStore = rootStore.visit;
const translations = rootStore.translations;
const t = fromMobx(() => translations.translation);
const locale = fromMobx(() => translations.locale);
const isReturningVisitor = fromMobx(() => guestDomain.isReturningVisitor);

function selectLanguage(selected: Locale) {
	translations.setLanguage(selected as Language);
	guestDomain.markAsReturningVisitor();
}

let nowTimer: ReturnType<typeof setInterval> | undefined;

const isStatusLoading = ref(true);
const guestIdentity = fromMobx(() => guestDomain.identity);

/**
 * Whether `/api/market` has ever returned usable data. Stays `false` while it hasn't, including
 * when the optional configuration endpoint can't be reached — `phase` below treats that the same
 * as registration being open, so the form is still available rather than blocking a guest behind
 * a "not open" screen the app can't actually confirm.
 */
const hasLoadedRegistration = fromMobx(() => session.currentState !== null);
/** Ticks every second so the registration form's countdown stays live. */
const now = ref(Date.now());

const phase = fromMobx(() =>
	hasLoadedRegistration.value
		? currentSessionPhase(session.marketEvent, new Date(now.value))
		: 'registration-open',
);
/**
 * Which of the signup card's states applies right now. An active visit always wins — see
 * `resolveGuestCardState` for the full precedence, which mirrors the server-side gate in
 * `guestRegistration.mts`. `isPreregistration` is always `false` here — the `/signup` route
 * renders `SignupView` instead, which is the only place that flag ever applies.
 */
const cardState = fromMobx(() =>
	resolveGuestCardState({
		phase: phase.value,
		isIdentified: guestDomain.isIdentified,
		isPreregistration: false,
		hasActiveVisit: visitStore.hasActiveVisit,
	}),
);
/** Once a market has run its course, there is nothing left to preregister for until an admin
 *  schedules the next one — unlike the "hasn't opened yet" case, which still welcomes it. */
const canPreregister = fromMobx(() => session.currentStatus !== SessionStatusEnum.ENDED);
/** The success-state copy differs between joining today's queue and signing up ahead of time. */
const successCopy = fromMobx(() =>
	guestFormContext(phase.value) === 'early'
		? { title: t.value.earlySuccessTitle, description: t.value.earlySuccessDescription }
		: { title: t.value.successTitle, description: t.value.successDescription },
);

function handleSubmitted(result: RegistrationSubmitResult) {
	if (result.kind !== 'registered') {
		return;
	}

	visitStore.submit(result.registration);
}

function cancelVisit() {
	if (!window.confirm(t.value.cancelVisitConfirm)) {
		return;
	}

	void visitStore.cancel();
}

onMounted(async () => {
	nowTimer = setInterval(() => {
		now.value = Date.now();
	}, 1_000);
	await Promise.all([session.getStatus().catch(() => undefined), visitStore.refresh()]);
	isStatusLoading.value = false;
});
onBeforeUnmount(() => {
	clearInterval(nowTimer);
});
const isSessionActive = fromMobx(() => session.isActive);
</script>

<template>
	<section class="guest-layout">
		<!-- Card that indicates who the guest has been identified as -->
		<GuestIdentityIndicator v-if="guestIdentity" :identity="guestIdentity" />

		<GuestLanguageHero
			v-if="!isReturningVisitor"
			:t="t"
			:locale="locale"
			@select-language="selectLanguage"
		/>

		<p v-if="isStatusLoading" class="status-loading" aria-live="polite">{{ t.statusLoading }}</p>
		<template v-else>
			<Card aria-live="polite">
				<template v-if="!isSessionActive">
					<GuestNotOpenState :t="t" :allow-preregister="canPreregister" />
				</template>
				<template v-else>
					<GuestVisitStatus
						v-if="cardState.kind === 'visit-status'"
						:success-title="successCopy.title"
						:success-description="successCopy.description"
						@cancel-visit="cancelVisit"
					/>
					<GuestRegistrationForm
						v-else-if="cardState.kind === 'form'"
						:context="cardState.context"
						:now="now"
						@submitted="handleSubmitted"
					/>
					<GuestNotOpenState v-else-if="cardState.kind === 'not-open'" :t="t" />
					<GuestRegistrationClosedState
						v-else-if="cardState.kind === 'registration-closed'"
						:t="t"
					/>
					<GuestServiceState v-else :t="t" :has-ended="cardState.kind === 'ended'" />
				</template>
			</Card>
		</template>
	</section>
</template>
