// src/components/guest-view/identity/NotificationOptIn.tsx
import styled from '@emotion/styled';
import { Button, Checkbox, FormControlLabel, Link } from '@mui/material';
import { observer } from 'mobx-react-lite';
import { useEffect, useState } from 'react';

import { useRootStore } from '../../../stores/react/store-context';
import { useTranslation } from '../../../stores/react/use-translation';

const Consent = styled.div`
	display: grid;
	gap: 18px;
`;

const Enabled = styled.p`
	margin: 0;
	font-weight: 700;
`;

const LegalLinks = styled.div`
	display: flex;
	justify-content: space-around;
	align-items: flex-start;
	gap: 16px;
	font-size: 14px;

	a {
		min-width: 0;
	}
`;

const SubmissionError = styled.p`
	color: var(--color-error);
	font-size: 13px;
	line-height: 1.4;
`;

/**
 * The SMS opt-in: the full consent language, a checkbox, and the button it gates.
 *
 * Consent belongs to the guest rather than a visit, so this is deliberately explicit — having a
 * phone number on file is not consent to be texted.
 */
export const NotificationOptIn = observer(function NotificationOptIn() {
	const t = useTranslation();
	const { guest } = useRootStore();
	const [smsConsent, setSmsConsent] = useState(false);

	useEffect(() => {
		void guest.loadNotificationSettings();
	}, [guest]);

	if (!guest.smsConfigured) {
		return <Consent className="notification-consent" />;
	}

	return (
		<Consent className="notification-consent">
			{guest.smsState === 'enabled' ? (
				<Enabled className="notification-enabled">{t.smsEnabled}</Enabled>
			) : (
				<>
					<FormControlLabel
						className="sms-consent"
						control={
							<Checkbox
								checked={smsConsent}
								onChange={(event) => setSmsConsent(event.target.checked)}
							/>
						}
						label={t.smsConsentLabel}
					/>
					<LegalLinks className="notification-legal-links">
						<Link href="/privacy">{t.privacyPolicy}</Link>
						<Link href="/terms">{t.termsAndConditions}</Link>
					</LegalLinks>
					<Button
						disabled={!smsConsent || guest.smsState === 'enabling'}
						onClick={() => void guest.enableSmsNotifications(smsConsent)}
					>
						{t.smsEnable}
					</Button>
					{guest.smsState === 'error' ? (
						<SubmissionError className="submission-error" role="alert">
							{t.smsError}
						</SubmissionError>
					) : null}
				</>
			)}
		</Consent>
	);
});

// src/components/guest-view/NotificationOptIn.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';

import { fromMobx } from '@/stores/hooks/from-mobx.ts';
import { useTranslation } from '@/stores/hooks/use-translation.ts';

import { translations, type Locale } from '../../locales';
import type { GuestStore } from '../../stores/guest.store';
import AppButton from '../AppButton.vue';

const props = defineProps<{ guest: GuestStore }>();
const guest = props.guest;
const t = useTranslation();
const smsConsent = ref(false);

onMounted(() => {
	void guest.loadNotificationSettings();
});
const smsConfigured = fromMobx(() => guest.smsConfigured);
const smsState = fromMobx(() => guest.smsState);
</script>

<template>
	<div class="notification-consent">
		<div v-if="smsConfigured" class="notification-option">
			<p v-if="smsState === 'enabled'" class="notification-enabled">{{ t.smsEnabled }}</p>
			<template v-else>
				<label class="sms-consent">
					<input v-model="smsConsent" type="checkbox" />
					<span>
						{{ t.smsConsentLabel }}
						<a href="/privacy">{{ t.privacyPolicy }}</a>
						·
						<a href="/terms">{{ t.termsAndConditions }}</a>
					</span>
				</label>
				<AppButton
					type="button"
					variant="secondary"
					:disabled="!smsConsent || smsState === 'enabling'"
					@click="guest.enableSmsNotifications(smsConsent)"
				>
					{{ t.smsEnable }}
				</AppButton>
				<p v-if="smsState === 'error'" class="submission-error" role="alert">
					{{ t.smsError }}
				</p>
			</template>
		</div>
	</div>
</template>

<style scoped>
.notification-consent {
	display: grid;
	gap: 18px;
}

.notification-option {
	display: grid;
	gap: 12px;
	padding: 18px;
	border-radius: var(--radius-md);
	background: var(--color-surface-soft);
}

.notification-option p {
	margin: 0;
	font-size: 14px;
}

.notification-enabled {
	font-weight: 700;
}

.sms-consent {
	display: flex;
	align-items: flex-start;
	gap: 10px;
}

.sms-consent input {
	flex: 0 0 auto;
	width: 20px;
	height: 20px;
	margin-top: 2px;
}

.sms-consent span {
	font-weight: 400;
	line-height: 1.55;
}

.submission-error {
	color: var(--color-error);
	font-size: 13px;
	line-height: 1.4;
}
</style>
