// src/components/guest-view/ScheduleInformation.tsx
import { observer } from 'mobx-react-lite';

import { useTranslation } from '../../stores/react/use-translation';
import { Alert } from '../ui/alerts/Alert';

/** The standing schedule, as a notice above the card. */
export const ScheduleInformation = observer(function ScheduleInformation() {
	const t = useTranslation();

	return (
		<Alert
			heading={t.guestView.scheduleInformation.heading}
			body={t.guestView.scheduleInformation.body}
		/>
	);
});

// src/components/guest-view/ScheduleInformation.vue
<script setup lang="ts">
import Alert from '@/components/ui/alerts/Alert.vue';

import type { Translation } from '../../locales';

defineProps<{
	t: Translation;
}>();
</script>

<template>
	<Alert
		:heading="t.guestView.scheduleInformation.heading"
		:body="t.guestView.scheduleInformation.body"
	/>
</template>

<style scoped></style>
