// src/components/ui/app-bar/AppBar.tsx
import { observer } from 'mobx-react-lite';
import type { ChangeEvent } from 'react';
import { Link, useLocation, useNavigate } from 'react-router';

import { languages } from '../../../locales';
import { useRootStore } from '../../../stores/react/store-context';
import { useTranslation } from '../../../stores/react/use-translation';
import type { Language } from '../../../stores/translation.store';

/**
 * The bar across the top of every screen: the mark, the language picker, and the guest/admin
 * toggle. Its styles live in `app-shell.css` rather than here, since the shell they belong to is
 * shared with the layout around it.
 */
export const AppBar = observer(function AppBar() {
	const t = useTranslation();
	const { guest, translations } = useRootStore();
	const navigate = useNavigate();
	const isAdmin = useLocation().pathname.startsWith('/admin');

	function setLocale(event: ChangeEvent<HTMLSelectElement>) {
		translations.setLanguage(event.target.value as Language);
	}

	return (
		<header className="topbar">
			<Link className="brand" to="/">
				<img className="brand-mark" src="/bay-compassion-logo.png" alt="" />
				<span>{t.marketName}</span>
			</Link>
			<div className="header-actions">
				{guest.isReturningVisitor ? (
					<label className="language-picker">
						<span className="sr-only">{t.language}</span>
						<select value={translations.locale} aria-label={t.language} onChange={setLocale}>
							{languages.map((language) => (
								<option key={language.code} value={language.code}>
									{language.label}
								</option>
							))}
						</select>
					</label>
				) : null}
				<button
					className="mode-button"
					type="button"
					onClick={() => void navigate(isAdmin ? '/' : '/admin')}
				>
					<svg
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						strokeWidth="2"
						aria-hidden="true"
					>
						<path d="M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM4 21a8 8 0 0 1 16 0" />
					</svg>
					{isAdmin ? t.guest : t.admin}
				</button>
			</div>
		</header>
	);
});

// src/components/ui/app-bar/AppBar.vue
<script setup lang="ts">
import { useRoute, useRouter } from 'vue-router';

import { languages } from '@/locales.ts';
import { fromMobx } from '@/stores/hooks/from-mobx.ts';
import type { Language } from '@/stores/translation.store.ts';
import { useStore } from '@/stores/use-store.ts';

interface Props {}

const props = defineProps<Props>();
const { guest, translations } = useStore();
const t = fromMobx(() => translations.translation);
const locale = fromMobx(() => translations.locale);
const isReturningVisitor = fromMobx(() => guest.isReturningVisitor);

const router = useRouter();
const route = useRoute();
const isAdmin = fromMobx(() => route.name === 'admin');

function setLocale(payload: Event) {
	const target = payload.target as HTMLSelectElement;

	translations.setLanguage(target.value as Language);
}

function toggleMode() {
	void router.push({ name: isAdmin.value ? 'guest' : 'admin' });
}
</script>

<template>
	<header class="topbar">
		<RouterLink class="brand" to="/">
			<img class="brand-mark" src="/bay-compassion-logo.png" alt="" />
			<span>{{ t.marketName }}</span>
		</RouterLink>
		<div class="header-actions">
			<label v-if="isReturningVisitor" class="language-picker">
				<span class="sr-only">{{ t.language }}</span>
				<select v-model="locale" :aria-label="t.language" @change="setLocale">
					<option
						v-for="language in languages"
						:key="language.code"
						:value="language.code as Language"
					>
						{{ language.label }}
					</option>
				</select>
			</label>
			<button class="mode-button" type="button" @click="toggleMode">
				<svg
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="2"
					aria-hidden="true"
				>
					<path d="M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM4 21a8 8 0 0 1 16 0" />
				</svg>
				{{ isAdmin ? t.guest : t.admin }}
			</button>
		</div>
	</header>
</template>

<style scoped></style>
