// src/components/legal/PrivacyPage.vue
<script setup lang="ts">
import { fromMobx } from '@/stores/hooks/from-mobx.ts';
import { useStore } from '@/stores/use-store.ts';

import LegalDocumentView from './LegalDocumentView.vue';
import privacyMarkdown from './privacy.md?raw';

const { translations } = useStore();
const t = fromMobx(() => translations.translation);
</script>

<template>
	<LegalDocumentView :back-label="t.backToGuest" :markdown="privacyMarkdown" />
</template>

<style scoped></style>

// src/components/legal/PrivacyPage.tsx
import { observer } from 'mobx-react-lite';
import { useNavigate } from 'react-router';

import { useTranslation } from '../../stores/react/use-translation';
import { LegalDocumentView } from './LegalDocumentView';
import privacyMarkdown from './privacy.md?raw';

/** The privacy document, as its own route. */
export const PrivacyPage = observer(function PrivacyPage() {
	const t = useTranslation();
	const navigate = useNavigate();

	return (
		<LegalDocumentView
			backLabel={t.backToGuest}
			markdown={privacyMarkdown}
			onBack={() => void navigate('/')}
		/>
	);
});
