// src/components/legal/TermsPage.tsx
import { observer } from 'mobx-react-lite';
import { useNavigate } from 'react-router';

import { useTranslation } from '../../stores/react/use-translation';
import { LegalDocumentView } from './LegalDocumentView';
import termsMarkdown from './terms.md?raw';

/** The terms document, as its own route. */
export const TermsPage = observer(function TermsPage() {
	const t = useTranslation();
	const navigate = useNavigate();

	return (
		<LegalDocumentView
			backLabel={t.backToGuest}
			markdown={termsMarkdown}
			onBack={() => void navigate('/')}
		/>
	);
});

// src/components/legal/TermsPage.vue
<script setup lang="ts">
import { fromMobx } from '@/stores/hooks/from-mobx.ts';
import { useStore } from '@/stores/use-store.ts';

import LegalDocumentView from './LegalDocumentView.vue';
import termsMarkdown from './terms.md?raw';

const { translations } = useStore();
const t = fromMobx(() => translations.translation);
</script>

<template>
	<LegalDocumentView :back-label="t.backToGuest" :markdown="termsMarkdown" />
</template>

<style scoped></style>
