// src/components/admin/QueueCallNext.tsx
import styled from '@emotion/styled';
import type { FormEvent } from 'react';

import { adminTranslations } from '../../adminLocales';
import { AppButton } from '../AppButton';

export type QueueCallNextProps = {
	waitingCount: number;
	busy?: boolean;
	count: number;
	onCountChange: (count: number) => void;
	onCall: () => void;
};

const Form = styled.form`
	display: grid;
	grid-template-columns: 110px minmax(0, 1fr);
	gap: 12px;
	align-items: end;
	margin-top: 0;
`;

/** How many waiting guests to call up at once, and the button that does it. */
export function QueueCallNext({
	waitingCount,
	busy,
	count,
	onCountChange,
	onCall,
}: QueueCallNextProps) {
	const t = adminTranslations.en;

	function handleSubmit(event: FormEvent<HTMLFormElement>) {
		event.preventDefault();
		onCall();
	}

	return (
		<Form className="call-next" onSubmit={handleSubmit}>
			<label>
				<span>{t.callNextCount}</span>
				<input
					type="number"
					min="1"
					max="50"
					step="1"
					required
					value={count}
					onChange={(event) => onCountChange(Number(event.target.value))}
				/>
			</label>
			<AppButton type="submit" disabled={busy || waitingCount === 0} label={t.callNext} />
		</Form>
	);
}

// src/components/admin/QueueCallNext.vue
<script setup lang="ts">
import { computed } from 'vue';

import { adminTranslations } from '../../adminLocales';
import type { Locale } from '../../locales';
import AppButton from '../AppButton.vue';

const props = defineProps<{ locale: Locale; waitingCount: number; busy?: boolean }>();

defineEmits<{ call: [] }>();
const count = defineModel<number>('count', { required: true });

const t = computed(() => adminTranslations[props.locale]);
</script>

<template>
	<form class="call-next" @submit.prevent="$emit('call')">
		<label>
			<span>{{ t.callNextCount }}</span>
			<input v-model.number="count" type="number" min="1" max="50" step="1" required />
		</label>
		<AppButton type="submit" :disabled="busy || waitingCount === 0">{{ t.callNext }}</AppButton>
	</form>
</template>

<style scoped>
.call-next {
	display: grid;
	grid-template-columns: 110px minmax(0, 1fr);
	gap: 12px;
	align-items: end;
	margin-top: 0;
}
</style>
