// src/components/admin/SessionView.tsx
import styled from '@emotion/styled';
import { observer } from 'mobx-react-lite';
import type { FormEvent } from 'react';

import { adminTranslations } from '../../adminLocales';
import type { GuestAdmission } from '../../services/guestAdmission';
import type { CurrentSessionState, SessionCommand } from '../../services/sessionStateMachine';
import type { VisitStatus } from '../../services/visitStateMachine';
import { useRootStore } from '../../stores/react/store-context';
import { AppButton } from '../AppButton';
import { AddGuestSection } from './AddGuestSection';
import { SessionBroadcastForm, type Broadcast } from './SessionBroadcastForm';
import { SessionGuestList } from './SessionGuestList';
import { SessionSettingsForm } from './SessionSettingsForm';
import type { AdminMarketEvent, ManualGuest, QueueGuest, SessionSettings } from './types';

export type SessionViewProps = {
	event: AdminMarketEvent | null;
	sessionState: CurrentSessionState;
	statuses: VisitStatus[];
	counts: Partial<Record<VisitStatus, number>>;
	statusLabels: Record<VisitStatus, string>;
	registeredGuests: QueueGuest[];
	admissions: GuestAdmission[];
	busy?: boolean;
	settings: SessionSettings;
	onSettingsChange: (settings: SessionSettings) => void;
	extensionMinutes: number;
	onExtensionMinutesChange: (minutes: number) => void;
	postponementMinutes: number;
	onPostponementMinutesChange: (minutes: number) => void;
	broadcast: Broadcast;
	onBroadcastChange: (broadcast: Broadcast) => void;
	onSaveSettings: () => void;
	onSaveAndStartRegistration: () => void;
	onPostponeRegistration: () => void;
	onExtendRegistration: () => void;
	onSaveCapacityOverride: () => void;
	onRun: (action: SessionCommand) => void;
	onAddGuest: (guest: ManualGuest) => void;
	onSendBroadcast: () => void;
	onNavigateQueue: () => void;
};

const StatGrid = styled.div`
	display: grid;
	grid-template-columns: repeat(2, 1fr);
	gap: 10px;
	margin-top: 14px;

	.stat-card {
		display: grid;
		gap: 2px;
		min-height: 92px;
		padding: 15px;
		border-radius: var(--radius-md);
		color: white;
		background: var(--color-brand);
	}

	.stat-card:first-of-type {
		grid-column: span 2;
	}

	.stat-card strong {
		font-family: var(--font-heading);
		font-size: 32px;
	}

	.stat-card span {
		font-size: 13px;
	}

	@media (min-width: 560px) {
		grid-template-columns: repeat(5, 1fr);

		.stat-card:first-of-type {
			grid-column: auto;
		}
	}
`;

const ActionCard = styled.section`
	display: flex;
	justify-content: space-between;
	gap: 14px;
	align-items: flex-start;

	.action-buttons {
		display: grid;
		gap: 10px;
		width: 100%;
	}

	@media (min-width: 560px) {
		align-items: center;

		.action-buttons {
			width: auto;
		}
	}
`;

const OverrideCard = styled.section`
	.override-grid {
		display: grid;
		gap: 18px;
	}

	.override-grid form {
		margin-top: 0;
		padding: 16px;
		border-radius: var(--radius-md);
		background: #f3f6f4;
	}

	.standalone-action {
		display: flex;
		justify-content: flex-end;
		margin-top: 18px;
		padding-top: 18px;
		border-top: 1px solid #dce3df;
	}

	@media (min-width: 560px) {
		.override-grid {
			grid-template-columns: 1fr 1fr;
		}
	}
`;

const ResetCard = styled.section`
	display: flex;
	flex-wrap: wrap;
	justify-content: space-between;
	align-items: center;
	gap: 16px;

	p {
		max-width: 560px;
		color: var(--color-text-subtle);
		line-height: 1.5;
	}

	.app-button.secondary {
		color: var(--color-error);
		box-shadow: inset 0 0 0 1.5px var(--color-error);
	}

	.app-button.secondary:hover:not(:disabled) {
		color: white;
		background: var(--color-error);
	}
`;

/** The session's own screen: whichever controls its current phase actually allows. */
export const SessionView = observer(function SessionView({
	event,
	sessionState,
	statuses,
	counts,
	statusLabels,
	registeredGuests,
	admissions,
	busy,
	settings,
	onSettingsChange,
	extensionMinutes,
	onExtensionMinutesChange,
	postponementMinutes,
	onPostponementMinutesChange,
	broadcast,
	onBroadcastChange,
	onSaveSettings,
	onSaveAndStartRegistration,
	onPostponeRegistration,
	onExtendRegistration,
	onSaveCapacityOverride,
	onRun,
	onAddGuest,
	onSendBroadcast,
	onNavigateQueue,
}: SessionViewProps) {
	const t = adminTranslations.en;
	const { translations } = useRootStore();

	const showsRegisteredGuests =
		!!event &&
		['registration_open', 'registration_closed', 'lottery_pending'].includes(sessionState);
	const showsBroadcast =
		!!event &&
		['registration_open', 'registration_closed', 'lottery_pending', 'service_started'].includes(
			sessionState,
		);

	function formatEventDate(value: string) {
		return new Intl.DateTimeFormat(translations.locale, {
			dateStyle: 'medium',
			timeStyle: 'short',
		}).format(new Date(value));
	}

	function submitting(handler: () => void) {
		return (formEvent: FormEvent<HTMLFormElement>) => {
			formEvent.preventDefault();
			handler();
		};
	}

	return (
		<>
			{sessionState === 'service_started' ? (
				<section className="admin-section">
					<h2>{t.overview}</h2>
					<StatGrid className="stat-grid">
						{statuses.map((status) => (
							<article key={status} className="stat-card">
								<strong>{counts[status] ?? 0}</strong>
								<span>{statusLabels[status]}</span>
							</article>
						))}
					</StatGrid>
				</section>
			) : null}

			{sessionState === 'inactive' ? (
				<SessionSettingsForm
					settings={settings}
					onSettingsChange={onSettingsChange}
					busy={busy}
					onSave={onSaveSettings}
					onSaveAndStart={onSaveAndStartRegistration}
				/>
			) : sessionState === 'scheduled' ? (
				<OverrideCard className="admin-section settings-card">
					<h2>{t.scheduled}</h2>
					<p>
						{t.scheduledFor} {formatEventDate(event!.registrationOpensAt)}
					</p>
					<div className="override-grid">
						<form onSubmit={submitting(onPostponeRegistration)}>
							<label>
								<span>{t.postponeByMinutes}</span>
								<input
									type="number"
									min="1"
									max="1440"
									step="1"
									required
									value={postponementMinutes}
									onChange={(changeEvent) =>
										onPostponementMinutesChange(Number(changeEvent.target.value))
									}
								/>
							</label>
							<AppButton
								type="submit"
								variant="secondary"
								disabled={busy}
								label={t.postponeRegistration}
							/>
						</form>
					</div>
					<div className="standalone-action">
						<AppButton
							type="button"
							disabled={busy}
							onClick={() => onRun('open_registration')}
							label={t.openRegistrationNow}
						/>
					</div>
				</OverrideCard>
			) : sessionState === 'registration_open' ? (
				<OverrideCard className="admin-section settings-card">
					<h2>{t.registrationOverrides}</h2>
					<p>{t.overridesHelp}</p>
					<div className="override-grid">
						<form onSubmit={submitting(onExtendRegistration)}>
							<label>
								<span>{t.extendRegistrationMinutes}</span>
								<input
									type="number"
									min="1"
									max="1440"
									step="1"
									list="registration-extension-options"
									required
									value={extensionMinutes}
									onChange={(changeEvent) =>
										onExtensionMinutesChange(Number(changeEvent.target.value))
									}
								/>
							</label>
							<datalist id="registration-extension-options">
								<option value="15" />
								<option value="30" />
								<option value="60" />
							</datalist>
							<AppButton
								type="submit"
								variant="secondary"
								disabled={busy}
								label={t.extendRegistration}
							/>
						</form>
						<form onSubmit={submitting(onSaveCapacityOverride)}>
							<label>
								<span>{t.capacity}</span>
								<input
									type="number"
									min="1"
									max="10000"
									required
									value={settings.capacity}
									onChange={(changeEvent) =>
										onSettingsChange({ ...settings, capacity: Number(changeEvent.target.value) })
									}
								/>
							</label>
							<AppButton
								type="submit"
								variant="secondary"
								disabled={busy}
								label={t.updateCapacity}
							/>
						</form>
					</div>
					<div className="standalone-action">
						<AppButton
							type="button"
							disabled={busy}
							onClick={() => onRun('close_registration')}
							label={t.closeRegistration}
						/>
					</div>
				</OverrideCard>
			) : sessionState === 'registration_closed' ? (
				<ActionCard className="admin-section action-card">
					<div>
						<h2>{t.closed}</h2>
						<p>{t.guestList}</p>
					</div>
					<div className="action-buttons">
						<AppButton
							type="button"
							variant="secondary"
							disabled={busy}
							onClick={() => onRun('reopen_registration')}
							label={t.reopenRegistration}
						/>
					</div>
				</ActionCard>
			) : sessionState === 'lottery_pending' ? (
				<ActionCard className="admin-section action-card">
					<div>
						<h2>{t.lotteryActions}</h2>
						<p>{t.lotteryPendingHelp}</p>
					</div>
					<div className="action-buttons">
						<AppButton
							type="button"
							disabled={busy}
							onClick={() => onRun('run_lottery')}
							label={t.runLottery}
						/>
					</div>
				</ActionCard>
			) : (
				<ActionCard className="admin-section action-card">
					<div>
						<h2>{t.serviceStarted}</h2>
						<p>{t.guestList}</p>
					</div>
					<div className="action-buttons">
						<AppButton type="button" onClick={onNavigateQueue} label={t.goToQueue} />
					</div>
				</ActionCard>
			)}

			{showsRegisteredGuests ? <SessionGuestList guests={registeredGuests} /> : null}

			{/* A worker can add someone by hand at any stage; only what "adding" means changes. */}
			<AddGuestSection admissions={admissions} busy={busy} onAddGuest={onAddGuest} />

			{showsBroadcast ? (
				<SessionBroadcastForm
					broadcast={broadcast}
					onBroadcastChange={onBroadcastChange}
					busy={busy}
					onSend={onSendBroadcast}
				/>
			) : null}

			{event ? (
				<ResetCard className="admin-section reset-card">
					<div>
						<h2>{t.resetSession}</h2>
						<p>{t.resetSessionHelp}</p>
					</div>
					<AppButton
						type="button"
						variant="secondary"
						disabled={busy}
						onClick={() => onRun('reset_session')}
						label={t.resetSession}
					/>
				</ResetCard>
			) : null}
		</>
	);
});

// src/components/admin/SessionView.vue
<script setup lang="ts">
import { computed } from 'vue';

import { adminTranslations } from '../../adminLocales';
import type { Locale } from '../../locales';
import type { GuestAdmission } from '../../services/guestAdmission';
import type { CurrentSessionState, SessionCommand } from '../../services/sessionStateMachine';
import type { VisitStatus } from '../../services/visitStateMachine';
import AppButton from '../AppButton.vue';
import AddGuestSection from './AddGuestSection.vue';
import SessionBroadcastForm from './SessionBroadcastForm.vue';
import SessionGuestList from './SessionGuestList.vue';
import SessionSettingsForm from './SessionSettingsForm.vue';
import type { AdminMarketEvent, ManualGuest, QueueGuest, SessionSettings } from './types';

const props = defineProps<{
	locale: Locale;
	event: AdminMarketEvent | null;
	sessionState: CurrentSessionState;
	statuses: VisitStatus[];
	counts: Partial<Record<VisitStatus, number>>;
	statusLabels: Record<VisitStatus, string>;
	registeredGuests: QueueGuest[];
	admissions: GuestAdmission[];
	busy?: boolean;
}>();
const emit = defineEmits<{
	saveSettings: [];
	saveAndStartRegistration: [];
	postponeRegistration: [];
	extendRegistration: [];
	saveCapacityOverride: [];
	run: [action: SessionCommand];
	addGuest: [guest: ManualGuest];
	sendBroadcast: [];
	navigateQueue: [];
}>();

const settings = defineModel<SessionSettings>('settings', { required: true });
const extensionMinutes = defineModel<number>('extensionMinutes', { required: true });
const postponementMinutes = defineModel<number>('postponementMinutes', { required: true });
const broadcast = defineModel<{ title: string; body: string }>('broadcast', { required: true });

const t = computed(() => adminTranslations[props.locale]);
const showsRegisteredGuests = computed(
	() =>
		!!props.event &&
		(props.sessionState === 'registration_open' || props.sessionState === 'registration_closed'),
);
const showsBroadcast = computed(
	() =>
		!!props.event &&
		['registration_open', 'registration_closed', 'service_started'].includes(props.sessionState),
);

function formatEventDate(value: string) {
	return new Intl.DateTimeFormat(props.locale, {
		dateStyle: 'medium',
		timeStyle: 'short',
	}).format(new Date(value));
}
</script>

<template>
	<section v-if="sessionState === 'service_started'" class="admin-section">
		<h2>{{ t.overview }}</h2>
		<div class="stat-grid">
			<article v-for="status in statuses" :key="status" class="stat-card">
				<strong>{{ counts[status] ?? 0 }}</strong>
				<span>{{ statusLabels[status] }}</span>
			</article>
		</div>
	</section>

	<SessionSettingsForm
		v-if="sessionState === 'inactive'"
		v-model="settings"
		:locale="locale"
		:busy="busy"
		@save="emit('saveSettings')"
		@save-and-start="emit('saveAndStartRegistration')"
	/>

	<section v-else-if="sessionState === 'scheduled'" class="admin-section settings-card">
		<h2>{{ t.scheduled }}</h2>
		<p>{{ t.scheduledFor }} {{ formatEventDate(event!.registrationOpensAt) }}</p>
		<div class="override-grid">
			<form @submit.prevent="emit('postponeRegistration')">
				<label
					><span>{{ t.postponeByMinutes }}</span
					><input
						v-model.number="postponementMinutes"
						type="number"
						min="1"
						max="1440"
						step="1"
						required
				/></label>
				<AppButton type="submit" variant="secondary" :disabled="busy">
					{{ t.postponeRegistration }}
				</AppButton>
			</form>
		</div>
		<div class="standalone-action">
			<AppButton type="button" :disabled="busy" @click="emit('run', 'open_registration')">
				{{ t.openRegistrationNow }}
			</AppButton>
		</div>
	</section>

	<section v-else-if="sessionState === 'registration_open'" class="admin-section settings-card">
		<h2>{{ t.registrationOverrides }}</h2>
		<p>{{ t.overridesHelp }}</p>
		<div class="override-grid">
			<form @submit.prevent="emit('extendRegistration')">
				<label
					><span>{{ t.extendRegistrationMinutes }}</span
					><input
						v-model.number="extensionMinutes"
						type="number"
						min="1"
						max="1440"
						step="1"
						list="registration-extension-options"
						required
				/></label>
				<datalist id="registration-extension-options">
					<option value="15"></option>
					<option value="30"></option>
					<option value="60"></option>
				</datalist>
				<AppButton type="submit" variant="secondary" :disabled="busy">
					{{ t.extendRegistration }}
				</AppButton>
			</form>
			<form @submit.prevent="emit('saveCapacityOverride')">
				<label
					><span>{{ t.capacity }}</span
					><input v-model.number="settings.capacity" type="number" min="1" max="10000" required
				/></label>
				<AppButton type="submit" variant="secondary" :disabled="busy">
					{{ t.updateCapacity }}
				</AppButton>
			</form>
		</div>
		<div class="standalone-action">
			<AppButton type="button" :disabled="busy" @click="emit('run', 'close_registration')">
				{{ t.closeRegistration }}
			</AppButton>
		</div>
	</section>

	<section v-else-if="sessionState === 'registration_closed'" class="admin-section action-card">
		<div>
			<h2>{{ t.lotteryActions }}</h2>
			<p>{{ t.closed }}</p>
		</div>
		<div class="action-buttons">
			<AppButton
				type="button"
				variant="secondary"
				:disabled="busy"
				@click="emit('run', 'reopen_registration')"
				>{{ t.reopenRegistration }}</AppButton
			>
			<AppButton type="button" :disabled="busy" @click="emit('run', 'run_lottery')">{{
				t.runLottery
			}}</AppButton>
		</div>
	</section>

	<section v-else class="admin-section action-card">
		<div>
			<h2>{{ t.serviceStarted }}</h2>
			<p>{{ t.guestList }}</p>
		</div>
		<div class="action-buttons">
			<AppButton type="button" @click="emit('navigateQueue')">{{ t.goToQueue }}</AppButton>
		</div>
	</section>

	<SessionGuestList v-if="showsRegisteredGuests" :locale="locale" :guests="registeredGuests" />

	<!-- A worker can add someone by hand at any stage; only what "adding" means changes. -->
	<AddGuestSection
		:locale="locale"
		:admissions="admissions"
		:busy="busy"
		@add-guest="emit('addGuest', $event)"
	/>

	<SessionBroadcastForm
		v-if="showsBroadcast"
		v-model="broadcast"
		:locale="locale"
		:busy="busy"
		@send="emit('sendBroadcast')"
	/>

	<section v-if="event" class="admin-section reset-card">
		<div>
			<h2>{{ t.resetSession }}</h2>
			<p>{{ t.resetSessionHelp }}</p>
		</div>
		<AppButton
			type="button"
			variant="secondary"
			:disabled="busy"
			@click="emit('run', 'reset_session')"
		>
			{{ t.resetSession }}
		</AppButton>
	</section>
</template>

<style scoped>
.stat-grid {
	display: grid;
	grid-template-columns: repeat(2, 1fr);
	gap: 10px;
	margin-top: 14px;
}
.stat-card {
	display: grid;
	gap: 2px;
	min-height: 92px;
	padding: 15px;
	border-radius: var(--radius-md);
	color: white;
	background: var(--color-brand);
}
.stat-card:first-child {
	grid-column: span 2;
}
.stat-card strong {
	font-family: var(--font-heading);
	font-size: 32px;
}
.stat-card span {
	font-size: 13px;
}
.action-card {
	display: flex;
	justify-content: space-between;
	gap: 14px;
	align-items: flex-start;
}
.action-buttons {
	display: grid;
	gap: 10px;
	width: 100%;
}
.override-grid {
	display: grid;
	gap: 18px;
}
.override-grid form {
	margin-top: 0;
	padding: 16px;
	border-radius: var(--radius-md);
	background: #f3f6f4;
}
.standalone-action {
	display: flex;
	justify-content: flex-end;
	margin-top: 18px;
	padding-top: 18px;
	border-top: 1px solid #dce3df;
}
.reset-card {
	display: flex;
	flex-wrap: wrap;
	justify-content: space-between;
	align-items: center;
	gap: 16px;
}
.reset-card p {
	max-width: 560px;
	color: var(--color-text-subtle);
	line-height: 1.5;
}
.reset-card :deep(.app-button.secondary) {
	color: var(--color-error);
	box-shadow: inset 0 0 0 1.5px var(--color-error);
}
.reset-card :deep(.app-button.secondary:hover:not(:disabled)) {
	color: white;
	background: var(--color-error);
}
@media (min-width: 560px) {
	.stat-grid {
		grid-template-columns: repeat(5, 1fr);
	}
	.stat-card:first-child {
		grid-column: auto;
	}
	.action-buttons {
		width: auto;
	}
	.override-grid {
		grid-template-columns: 1fr 1fr;
	}
	.action-card {
		align-items: center;
	}
}
</style>
