// src/components/admin/SessionBroadcastForm.tsx
import type { FormEvent } from 'react';

import { adminTranslations } from '../../adminLocales';
import { AppButton } from '../AppButton';

export type Broadcast = { title: string; body: string };

export type SessionBroadcastFormProps = {
	busy?: boolean;
	broadcast: Broadcast;
	onBroadcastChange: (broadcast: Broadcast) => void;
	onSend: () => void;
};

/** A push/SMS message to everyone with a live visit in this session. */
export function SessionBroadcastForm({
	busy,
	broadcast,
	onBroadcastChange,
	onSend,
}: SessionBroadcastFormProps) {
	const t = adminTranslations.en;

	function handleSubmit(event: FormEvent<HTMLFormElement>) {
		event.preventDefault();
		onSend();
	}

	return (
		<section className="admin-section broadcast-card">
			<h2>{t.broadcastTitle}</h2>
			<p>{t.broadcastHelp}</p>
			<form onSubmit={handleSubmit}>
				<label>
					<span>{t.broadcastTitleLabel}</span>
					<input
						type="text"
						maxLength={100}
						required
						value={broadcast.title}
						onChange={(event) => onBroadcastChange({ ...broadcast, title: event.target.value })}
						onBlur={(event) =>
							onBroadcastChange({ ...broadcast, title: event.target.value.trim() })
						}
					/>
				</label>
				<label>
					<span>{t.broadcastMessageLabel}</span>
					<textarea
						maxLength={500}
						rows={4}
						required
						value={broadcast.body}
						onChange={(event) => onBroadcastChange({ ...broadcast, body: event.target.value })}
						onBlur={(event) => onBroadcastChange({ ...broadcast, body: event.target.value.trim() })}
					/>
				</label>
				<AppButton type="submit" disabled={busy} label={t.broadcastSend} />
			</form>
		</section>
	);
}

// src/components/admin/SessionBroadcastForm.vue
<script setup lang="ts">
import { computed } from 'vue';

import { adminTranslations } from '../../adminLocales';
import type { Locale } from '../../locales';
import AppButton from '../AppButton.vue';

const props = defineProps<{ locale: Locale; busy?: boolean }>();
const emit = defineEmits<{ send: [] }>();
const broadcast = defineModel<{ title: string; body: string }>({ required: true });

const t = computed(() => adminTranslations.en);
</script>

<template>
	<section class="admin-section broadcast-card">
		<h2>{{ t.broadcastTitle }}</h2>
		<p>{{ t.broadcastHelp }}</p>
		<form @submit.prevent="emit('send')">
			<label>
				<span>{{ t.broadcastTitleLabel }}</span>
				<input v-model.trim="broadcast.title" type="text" maxlength="100" required />
			</label>
			<label>
				<span>{{ t.broadcastMessageLabel }}</span>
				<textarea v-model.trim="broadcast.body" maxlength="500" rows="4" required></textarea>
			</label>
			<AppButton type="submit" :disabled="busy">{{ t.broadcastSend }}</AppButton>
		</form>
	</section>
</template>
